/**
 * BacklinkFlow v0.3 — GitHub awesome-list contribution generator.
 *
 * DRY-RUN ONLY. Generates the markdown snippet (product name, one-line
 * description, link) formatted for an awesome-list README contribution,
 * plus the PR body and step-by-step instructions. Never opens a PR and
 * never pushes to another repo.
 *
 * Awesome-list convention (awesome-lint friendly):
 *   `- [Product Name](https://site.com) — One-line description, ≤80 chars, no period.`
 */
import { loadConfig } from './config.js';

export interface AwesomeSnippet {
  /** The markdown list item, e.g. `- [Name](url) — description` */
  markdown: string;
  /** Which awesome-list section it fits best (heuristic). */
  suggestedSection: string;
}

/** Pick the most likely awesome-list section for the config content. */
export function suggestSection(cfg: ReturnType<typeof loadConfig>): string {
  const hay = [
    cfg.siteName,
    cfg.siteDescription || '',
    (cfg.tags || []).join(' '),
    cfg.contentDomain || '',
  ].join(' ').toLowerCase();
  const find = (keys: string[]): boolean => keys.some((k) => hay.includes(k));
  if (find(['ai', 'llm', 'machine learning', 'gpt', 'generative'])) return 'AI';
  if (find(['saas', 'product', 'startup', 'tool', 'app'])) return 'Products & Tools';
  if (find(['developer', 'dev', 'api', 'cli', 'open source', 'self-host'])) return 'Developer Tools';
  if (find(['travel', 'blog', 'content', 'seo'])) return 'Content & SEO';
  return 'Tools';
}

/** Build the one-line description from config. */
export function buildOneLiner(cfg: ReturnType<typeof loadConfig>): string {
  const fallback = cfg.contentDomain || cfg.siteName || 'a product';
  const raw = cfg.siteDescription || `A free tool for ${fallback}.`;
  let line = raw.trim().replace(/\s+/g, ' ').replace(/\.$/, '');
  // awesome-lint caps list descriptions at 80 chars, no trailing period.
  if (line.length > 80) line = `${line.slice(0, 77)}…`;
  return line;
}

/** Build the markdown list item. */
export function buildSnippet(cfg: ReturnType<typeof loadConfig>): AwesomeSnippet {
  const name = cfg.siteName || 'Your Product';
  const url = cfg.siteUrl || 'https://example.com';
  const desc = buildOneLiner(cfg);
  return {
    markdown: `- [${name}](${url}) — ${desc}`,
    suggestedSection: suggestSection(cfg),
  };
}

/** Full PR body for the awesome-list contribution (dry-run output). */
export function buildPrBody(cfg: ReturnType<typeof loadConfig>, repo: string): string {
  const { markdown, suggestedSection } = buildSnippet(cfg);
  return [
    `## Add ${cfg.siteName || 'Product'} to ${repo}`,
    '',
    `### Checklist`,
    '',
    '- [x] The snippet follows awesome-list formatting (\`- [Name](url) — one-liner\`)',
    '- [x] Description is ≤80 chars, no trailing period',
    "- [x] I have read the repository's contribution guidelines",
    '',
    `### Snippet`,
    '',
    '```markdown',
    markdown,
    '```',
    '',
    `### Details`,
    '',
    `- **Product:** ${cfg.siteName || '(unset)'}`,
    `- **URL:** ${cfg.siteUrl || '(unset)'}`,
    `- **Suggested section:** ${suggestedSection}`,
    `- **Category/tags:** ${(cfg.tags || []).join(', ') || '(none)'}`,
    '',
    '---',
    '',
    `_Generated by [BacklinkFlow](https://github.com/imsankz/backlinkflow) \`awesome\` (dry-run). Manual PR only — the tool never pushes._`,
  ].join('\n');
}

/** Human instructions to turn the snippet into a real contribution. */
export function buildInstructions(repo: string, snippet: AwesomeSnippet): string {
  return [
    `1. Fork https://github.com/${repo}`,
    `2. Clone, then edit the README.md of the awesome list`,
    `3. Add this line to the ${snippet.suggestedSection} section (find the closest match):`,
    '',
    `   ${snippet.markdown}`,
    '',
    '4. Commit (conventional: `docs: add <product>`) and push to your fork',
    '5. Open a PR against the upstream repo — paste the PR body below',
    '6. Respect each list\'s contribution guide; some want alphabetical order',
  ].join('\n');
}
